# Configuration for cubi-demux.
#
# This file is a YAML configuration file.  The default configuration is
# preconfigured for the BIH cluster and has to be adjusted accordingly.

# Configuration for the demultiplexing.
cubi_demux:
  input_dir: null  # path to input, override with `--input-dir`
  num_threads: 8   # number of threads, override with `--num-threads`

# Configuration for the screening after demultiplexing.  You should provide
# a list of BWA-indexed references and the path to a Kraken DB.  The data
# will first be subsampled and screened versus the given model organisms'
# genomes.  Unaligned reads will then be screened by Kraken.
hts_screen:
  sample_rate: 0.001  # sample this rate of reads for screening
  kraken_db: '/fast/projects/cubit/current/static_data/app_support/kraken/0.10.5-cubi20160426/minikraken_20141208'
  references:
    - name: 'H. sapiens'
      bwa_index: '/fast/projects/cubit/current/static_data/precomputed/BWA/0.7.12/GRCh37/hs37/hs37.fa'
    - name: 'M. musculus'
      bwa_index: '/fast/projects/cubit/current/static_data/precomputed/BWA/0.7.12/NCBIM37/sanger/NCBIM37_um.fa'
    - name: 'D. rerio'
      bwa_index: '/fast/projects/cubit/current/static_data/precomputed/BWA/0.7.12/danRer10/ucsc/danRer10.fa'
    - name: 'D. melanogaster'
      bwa_index: '/fast/projects/cubit/current/static_data/precomputed/BWA/0.7.12/dm6/ucsc/dm6.fa'
    - name: 'S. cerevisiae'
      bwa_index: '/fast/projects/cubit/current/static_data/precomputed/BWA/0.7.12/sacCer3/ucsc/sacCer3.fa'
    - name: 'E. coli'
      bwa_index: '/fast/projects/cubit/current/static_data/precomputed/BWA/0.7.12/ecoli/GCA_000005845.2_ASM584v2/ecoli.fa'
    - name: 'Phi X 174'
      bwa_index: '/fast/projects/cubit/current/static_data/precomputed/BWA/0.7.12/phix/illumina/phix.fa'
    - name: 'Univec 9'
      bwa_index: '/fast/projects/cubit/current/static_data/precomputed/BWA/0.7.12/UniVec/9/UniVec.fa'

# The sample sheet.  Either a path to the sample sheet or a dict with the
# sample sheet.  The path can can also be set with `--sample-sheet`.
sample_sheet: null
