about:
  home: https://support.illumina.com/downloads/bcl2fastq-conversion-software-v217.html

package:
  name: bcl2fastq2
  version: '2.17.1.14'

build:
  number: 2
  skip: False

test:
  commands:
  - bcl2fastq --help

requirements:
  build:
  - gcc ==4.8.5
  - libgcc ==7.2.0
  - cmake ==3.10.0
  - zlib >=1.2.8
  run:
  - libgcc >=4.8.5
  - zlib >=1.2.8
